version: '3'

services:
  vote:
    build: ./vote  # Directorio donde está el Dockerfile de tu aplicación
    depends_on:
      - redis
    ports:
      - "5000:80"
    networks:
      - back-tier
 
  result: 
    build: ./result
    ports:
      - "5001:80"
    networks:
      - back-tier

  worker:
    build:
      context: ./worker
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    networks:
      - back-tier

  db: 
    build: ./db
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    networks:
      - back-tier  

volumes: 
  postgres_data:

networks:
  back-tier:
    driver: bridge  # Usa la red bridge por defecto