version: '3.8'  # Asegúrate de que esta línea esté actualizada

services:

  frontend:
    build: ./frontend
    depends_on:
      - redis
      - db
      - worker
      - kafka
    ports:
      - "8000:8000"
    networks:
      - back-tier

  worker:
    build:
      context: ./worker
    depends_on:
      - redis
      - db
      - kafka
    ports:
      - "5000:5000"
    networks:
      - back-tier

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    networks:
      - back-tier

  db: 
    build: ./db
    container_name: db
    ports:
      - "3306:3306"
    volumes: 
      - mysql_data:/var/lib/mysql  
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - back-tier  

  zookeeper:
    image: confluentinc/cp-zookeeper:latest  # Usa la imagen actualizada de Confluent
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_ZNODE_PARENT: /confluent
    networks:
      - back-tier

  kafka:
    image: confluentinc/cp-kafka:latest  # Usa la imagen actualizada de Confluent
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    networks:
      - back-tier
  
  spark:
    image: bitnami/spark:latest  # Cambia por la imagen que prefieras
    ports:
      - "8080:8080"  # Asegúrate de usar el puerto correcto
    networks:
      - back-tier

volumes: 
  mysql_data:

networks:
  back-tier:
    driver: bridge
