# Usa la imagen oficial de Redis como base
FROM redis:alpine

# Configura Redis para usar un archivo de configuración personalizado (opcional)
# COPY redis.conf /usr/local/etc/redis/redis.conf

# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]

# O simplemente usa la configuración predeterminada
CMD ["redis-server"]